services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - wishlist_storage:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  wishlist_storage:
